---
title: "interation and listcols"
author: "Luan Mengxiao"
date: 2023-10-31
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
```

```{r}
set.seed(12345)
```

### lists

```{r}
vec_numeric = 1:4
vec_char = c("my", "name", "is", "jeff")

tibble(num = vec_numeric, char = vec_char)
```

Different stuff with different lengths

```{r}
l = list(
  vec_numeric = 1:5,
  vec_char = LETTERS,
  matrix = matrix(1:10, nrow = 5, ncol = 2),
  summary = summary(rnorm(100))
)
```

Accessing lists

```{r}
l$vec_char
l[[2]]
l[["summary"]]
```

### loops

```{r}
list_norm_samples = 
  list(
    a = rnorm(20, 1, 5),
    b = rnorm(20, 0, 7),
    c = rnorm(20, 20, 1),
    d = rnorm(20, -45, 13)
  )
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

```{r}
mean_and_sd(list_norm_samples$a)
mean_and_sd(list_norm_samples$b)
mean_and_sd(list_norm_samples$c)
mean_and_sd(list_norm_samples$d)
```

```{r}
output_mean_sd = vector("list", length = 4)
output_median = vector("list", length = 4)

for(i in 1:4){
  output_mean_sd[[i]] = mean_and_sd(list_norm_samples[[i]])
  output_median[[i]] = median(list_norm_samples[[i]])
}
```

### use `map`

```{r}
output_mean_sd = map(list_norm_samples, mean_and_sd)

output_median = map(list_norm_samples, median)

output_summary = map(list_norm_samples, summary)
```

### create DF

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norm_samples
  )
```

```{r}
mean_and_sd(listcol_df$samp[[1]])
mean_and_sd(listcol_df$samp[[2]])
mean_and_sd(listcol_df$samp[[3]])
mean_and_sd(listcol_df$samp[[4]])

map(listcol_df$samp, mean_and_sd)

listcol_df |>
  mutate(mean_sd = map(samp, mean_and_sd),
         median = map(samp, median)) |>
  pull(mean_sd)
  
listcol_df |>
  mutate(mean_sd = map(samp, mean_and_sd),
         median = map(samp, median)) |>
  select(name, mean_sd) |>
  unnest(mean_sd)
```

### NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)
```

Import function

```{r}
nsduh_table <- function(html, table_number, outcome_name) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_number) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent),
      outcome = outcome_name) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
}
```

import data using a `for` loop

```{r}
table_input = list(1, 4, 5)
name_input = list("marj", "cocaine", "heroin")

output = vector("list", length = 3)

for(i in c(1:3)){
  output[[i]] = nsduh_table(nsduh_html, table_input[[i]], name_input[[i]])
}

nsduh_df = bind_rows(output)
```

Try again, using maps!

```{r}
nsduh_import <- function(html, table_number) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_number) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent)) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
}

nsduh_df = 
  tibble(
    name = c("marj", "cocaine", "heroin"),
    number = c(1, 4, 5)
  ) |>
  mutate(table = map(number, nsduh_import, html = nsduh_html)) |>
  unnest(table)

map(nsduh_df$number, nsduh_import, html = nsduh_html)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_nest_df = 
  weather_df |>
  nest(df = date:tmin)
```

can i regress `tmax` on `tmin` for each of these?

```{r}
central_park_df = 
  weather_nest_df |>
  pull(df) |>
  nth(1)
```

fit a linear regression for central park

```{r}
lm(tmax~tmin, data = central_park_df)
```

```{r}
weather_lm = function(df){
  lm(tmax~tmin, data = df)
}

weather_lm(central_park_df)
```

let's try a `for` loop

```{r}
input_list = weather_nest_df |> pull(df)
output_list = vector("list", length = 3)

for(i in 1:3){
  output_list[[i]] = weather_lm(input_list[[i]])
}

weather_nest_df |>
  mutate(models = map(df, weather_lm))
```

